# Workflow to build and deploys a Node.js application to an Azure App Service
# representing a production environment using reusable workflows.
#
# Triggered on pushing into main.

name: Deploy to Production

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    uses: gidavies/simplewebapp/.github/workflows/build.yml@main
    with:
      node_version: '16.x'
  
  publish:
    uses: gidavies/simplewebapp/.github/workflows/containerise.yml@main
    needs: build

  deploy:
      # Don't run this job if the commit message contains 'skip deploy'
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    uses: gidavies/simplewebapp/.github/workflows/deploy_to_azure_oidc.yml@main
    with:
      envName: 'Production'
      appServiceName: 'simplewebapp-gd-prod'
      acrName: 'simplewebapp'
      tagName: 'simplewebapp'
    secrets:
      # PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    needs: build