# Workflow to build and deploys a Node.js application to an Azure App Service
# representing a test environment using reusable workflows.
#
# Triggered by applying a label in a PR.

name: Deploy to Test

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    uses: gidavies/simplewebapp/.github/workflows/build.yml@main
    with:
      node_version: '20.x'

  deploy:
    if: github.event.label.name == 'deploy to test'
    uses: gidavies/simplewebapp/.github/workflows/deploy_to_azure_oidc.yml@main
    with:
      envName: 'Test'
      appServiceName: 'simplewebapp-gd-test'
      acrName: 'simplewebapp'
      tagName: 'simplewebapp'
    secrets:
      # PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    needs: build