# Workflow to run as part of a PR

name: PR checks

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: gidavies/simplewebapp/.github/workflows/build.yml@main
    with:
      node_version: '20.x'
